// LOGIN
export const AUTH_LOGIN_LOADING = 'AUTH_LOGIN_LOADING'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_LOGIN_FAILER = 'AUTH_LOGIN_FAILER'
export const AUTH_LOGIN_REST = 'AUTH_LOGIN_REST'
export const IS_AUTH = 'IS_AUTH'
